#define JOINREQUEST 1
#define JOINRESPONSE 2 
#define ASKFILELIST 3
#define FILELIST 4
#define ASKFILE 5 
#define ASKFILERESPONSE 6
#define GETFILE 7
#define GETFILERESPONSE 8
#define SENDFILE 9
#define SENDFILERESPONSE 10
#define DELETEFILE 11
#define DELETEFILERESPONSE 12
#define ERROR -1

#define BUFSIZE 1024
#define CHUNKSIZE 4096
